[package]
name = "mandelbrot_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "mandelbrot_rs"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
num = "0.4.3"
pyo3 = { version = "0.22.2", features = ["extension-module"] }
